# This file configures the Dart analyzer for static analysis.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    annotate_overrides: true
    avoid_print: true
    curly_braces_in_flow_control_structures: true
    sort_constructors_first: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
